version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: college_schedule_db
    environment:
      POSTGRES_DB: ScheduleDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: